### ISSUE TITLE
ImportError: No module named 'Stemmer'

### ISSUE THREAD

**Issue by loveJasmine** [sisaman/npglm#1]
mldl@ub1604:~/ub16_prj/npglm$ python3 experiment.py 
Traceback (most recent call last):
  File "experiment.py", line 31, in <module>
    from features.dblp.extraction import run as dblp_feature
  File "/home/mldl/ub16_prj/npglm/features/dblp/extraction.py", line 1, in <module>
    import Stemmer
ImportError: No module named 'Stemmer'

**Comment by sisaman** [comment]
pip install --upgrade pystemmer

**Comment by loveJasmine** [comment]
it works
